addons:
  sonarqube:
    organization: klieber-github
    token:
      secure: DQAuVUJIQG3w9TlsIU24rcCjZUnqtkGa2uFWjyN4dYL/VRZp9J8SYhpsqef8dOtGgzPVsxyRumqhXwFo1/h1HJp1O9d8IVMC+AGgzLZeH1kApODcHNTIaAMs15h+LDHwKSODMV9wjlssL3q5qD97DbjBbjOrQymkGyga4/gNc6Q=
after_success:
- mvn clean test jacoco:report coveralls:report
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
install: travis_retry bundle install
jdk:
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: bundle exec rake cucumber && mvn sonar:sonar
sudo: false
